Keeps crashing on updating of user details thru firebase
error shown in logcat ->

FATAL EXCEPTION: main
                                                                                                    Process: eu.tutorials.ticktock, PID: 10835
                                                                                                    java.lang.NullPointerException: Argument must not be null
                                                                                                    	at com.bumptech.glide.util.Preconditions.checkNotNull(Preconditions.java:29)
                                                                                                    	at com.bumptech.glide.util.Preconditions.checkNotNull(Preconditions.java:23)
                                                                                                    	at com.bumptech.glide.RequestBuilder.into(RequestBuilder.java:669)
                                                                                                    	at eu.tutorials.ticktock.activites.MainActivity.updateNavigationUserDetails(MainActivity.kt:92)
                                                                                                    	at eu.tutorials.ticktock.firebase.FireStoreClass$loadUserData$1.invoke(FireStoreClass.kt:66)
                                                                                                    	at eu.tutorials.ticktock.firebase.FireStoreClass$loadUserData$1.invoke(FireStoreClass.kt:56)
                                                                                                    	at eu.tutorials.ticktock.firebase.FireStoreClass.loadUserData$lambda$4(FireStoreClass.kt:56)
                                                                                                    	at eu.tutorials.ticktock.firebase.FireStoreClass.$r8$lambda$SX2eYaHujUWnbrBBBjSqI3Lu5D0(Unknown Source:0)
                                                                                                    	at eu.tutorials.ticktock.firebase.FireStoreClass$$ExternalSyntheticLambda0.onSuccess(Unknown Source:2)
                                                                                                    	at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7842)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)